language: node_js



node_js:
  - '10'



before_install:
  - npm i -g npm@latest

install:
  
  - npm install -g firebase-tools
  
after_success:
  - firebase deploy --token $FIREBASE_TOKEN

before_script:

script:
  - echo "Deploying..!"
  
  - npm run build --prod

git:
  depth: 1
